[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.14.0" }
serde = "1.0"
sha2 = "0.10.6"
hex = { version = "0.4", default-features = false}
